services:
  test_app:
    build:
      context: .
    container_name: test_app
    command: uvicorn main:app --host 0.0.0.0 --port 7000 --reload
    depends_on:
      - test_db
    environment:
      PYTHONPATH: /app
      ASYNC_DATABASE_URL: postgresql+asyncpg://test_user:test_password@postgres_test:5432/test_db
      SYNC_DATABASE_URL: postgresql+psycopg2://test_user:test_password@postgres_test:5432/test_db
    volumes:
      - ./src:/app

  test_db:
    image: postgres:16
    container_name: postgres_test
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      retries: 5
