server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    location / {
        root    /usr/share/nginx/html;
        try_files $uri $uri/ index.html;
        add_header Cache-Control "public, max-age=10";
        access_log off;
    }

    location /api/users {
        proxy_pass http://users_app:8000/v1/api/users;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/tasks {
        proxy_pass http://tasks_app:7000/v1/api/tasks;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/tasks/ {
        proxy_pass http://tasks_app:7000/v1/api/tasks/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
